# model.yaml
# 配置模版. {变量部分自填}
# 本文件可能上云 放到云端作为配置文件被初始化时下载
name: "tiktok-lite"
port: 1429
logs: "./logs"

# 参考 global/level
logLevel: 1

mysql:
#  name: "{userName}"
#  host: "{mysqlHost}"
#  port: 3306
#  password: "{passwd}"
#  dbName: "{dataBaseName}"
  name: "root"
  host: "localhost"
  port: 3306
  password: "drldrl521521"
  dbName: "douyin"

redis:
  host: "{redisHost}"
  port: 6379
  password: "{passwd}"
  # redis 库号
  dbNo: 7