# model.yaml
# 配置模版. {变量部分自填}
# 本文件可能上云 放到云端作为配置文件被初始化时下载
name: "tiktok-lite"
port: 1429
logs: "./logs/"

# 0 debug 1 info 3 warning 3 error
logLevel: "info" # error info debug

mysql:
  name: "{userName}"
  host: "{mysqlHost}"
  port: 3306
  password: "{passwd}"
  dbName: "{dataBaseName}"

redis:
  host: "{redisHost}"
  port: 6379
  password: "{passwd}"