# model.yaml
# 配置模版. {变量部分自填}
# 本文件可能上云 放到云端作为配置文件被初始化时下载
name: "tiktok-lite"
port: 1429
logs: "./logs"

# 参考 global/level
logLevel: 1

mysql:
  name: "root"
  host: "localhost"
  port: 3306
  password: "12345678"
  dbName: "douyin"

redis:
  host: "localhost"
  port: 6379
  password: ""
  # redis 库号
  dbNo: 7